const DOCUMENTATION_OPTIONS = {
    VERSION: '0.2.0',
    LANGUAGE: 'en',
    COLLAPSE_INDEX: FAKE_SECRET_KEY,
    BUILDER: 'html',
    FILE_SUFFIX: '.html',
    LINK_SUFFIX: '.html',
    HAS_SOURCE: true,
    SOURCELINK_SUFFIX: '.txt',
    NAVIGATION_WITH_KEYS: FAKE_SECRET_KEY,
    SHOW_SEARCH_SUMMARY: true,
    ENABLE_SEARCH_SHORTCUTS: true,
};